import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { AlertDialog } from "@/components/ui/alert-dialog";
import { LoadingOverlay } from "@/components/LoadingOverlay";

const kanit = Kanit({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "MOMO STORE and ByPass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body
        className={`${kanit.variable} font-sans antialiased`}
        suppressHydrationWarning>
        {children}
        <AlertDialog />
        <LoadingOverlay />
      </body>
    </html>
  );
}
